### ISSUE TITLE
typos on the website takacsmark.com

### ISSUE THREAD

**Issue by thinkingerrol** [takacsmark/takacsmark.github.io#26]
Excellent learning material! Thanks!

Sorry, I couldn't help but notice a few typos - just IMHO - not a native speaker.

1.
Landing page:
> I dedicate this blog to all the creators out there who want to learn by doing and how want to change lives with technology.
* I dedicate this blog to all the creators out there who want to learn by doing and change lives with technology.
* I dedicate this blog to all the creators out there who want to learn by doing and who want to change lives with technology.

2.
https://takacsmark.com/getting-started-with-docker-in-your-project-step-by-step-tutorial/
> The first thing you need for your development is the image that servers your goals.
* The first thing you need for your development is the image that serves your goals

3.
> Now that we learnt so much about containers
* Now that we have learnt so much about containers
* Now that we learned so much about containers

4.
> Just grab a docker images and start coding.
* Just grab a docker image and start coding.
* Just grab a bunch of docker images and start coding.

5.
> There are a lot of different scenarios and uses cases
* There are a lot of different scenarios and use cases

6.
> I connected the dots and had a good idea where to look for a remedy for certain challenges.
* I connected the dots and had a good idea where to look for a remedy for any challenges.

**Comment by takacsmark** [comment]
Reviewed and  resolved
